/* ═══════════════════════════════════════════════════════════
   SAINT SEIYA — EPISODES DATA  /js/episodes-data.js
═══════════════════════════════════════════════════════════ */

const EPISODES = {
  1: {
    title: "Gran Torneo Galáctico",
    subtitle: "Episodios 1–26 · 1986–1987 · Arco introductorio",
    icon: "⚔️",
    list: [
      { num:1,  title:"¡El Joven que Despierta el Cosmo!",        arc:"Torneo Galáctico" },
      { num:2,  title:"¡El Santo de Bronce de Pegaso!",           arc:"Torneo Galáctico" },
      { num:3,  title:"¡El Enemigo es un Compañero!",             arc:"Torneo Galáctico" },
      { num:4,  title:"¡El Despertar del Cosmo Dorado!",          arc:"Torneo Galáctico" },
      { num:5,  title:"¡El Gran Coliseo del Torneo!",             arc:"Torneo Galáctico" },
      { num:6,  title:"¡La Flecha de la Constelación del Acuario!",arc:"Torneo Galáctico" },
      { num:7,  title:"¡El Dragón Plateado Contraataca!",         arc:"Torneo Galáctico" },
      { num:8,  title:"¡Revive el Meteoro de Pegaso!",            arc:"Torneo Galáctico" },
      { num:9,  title:"¡La Cadena de Andrómeda!",                 arc:"Torneo Galáctico" },
      { num:10, title:"¡El Cisne Blanco de las Nieves!",          arc:"Torneo Galáctico" },
      { num:11, title:"¡El Fénix Negro!",                         arc:"Torneo Galáctico" },
      { num:12, title:"¡Hermanos Frente a Frente!",               arc:"Torneo Galáctico" },
      { num:13, title:"¡La Flecha de la Diosa!",                  arc:"Torneo Galáctico" },
      { num:14, title:"¡El Escudo de Rosetón Destruye Todo!",     arc:"Torneo Galáctico" },
      { num:15, title:"¡La Gran Final del Torneo!",               arc:"Torneo Galáctico" },
      { num:16, title:"¡El Secreto de la Armadura Dorada!",       arc:"Torneo Galáctico" },
      { num:17, title:"¡Seiya Vs el Santo de Géminis!",           arc:"Torneo Galáctico" },
      { num:18, title:"¡El Poder del Séptimo Sentido!",           arc:"Torneo Galáctico" },
      { num:19, title:"¡La Verdad del Santuario!",                arc:"Torneo Galáctico" },
      { num:20, title:"¡El Cofre de Atenea!",                     arc:"Torneo Galáctico" },
      { num:21, title:"¡Los Cuatro Santos de Bronce!",            arc:"Torneo Galáctico" },
      { num:22, title:"¡La Misión Sagrada!",                      arc:"Torneo Galáctico" },
      { num:23, title:"¡Seiya Cae en la Trampa!",                 arc:"Torneo Galáctico" },
      { num:24, title:"¡El Espejo del Alma!",                     arc:"Torneo Galáctico" },
      { num:25, title:"¡La Hermana Perdida!",                     arc:"Torneo Galáctico" },
      { num:26, title:"¡Hacia el Santuario de Atenea!",           arc:"Torneo Galáctico" },
    ]
  },
  2: {
    title: "Las 12 Casas del Zodiaco",
    subtitle: "Episodios 27–73 · 1987–1988 · El arco más icónico",
    icon: "🏛️",
    list: [
      { num:27, title:"¡Las 12 Casas del Zodiaco!",               arc:"Santuario" },
      { num:28, title:"¡Batalla en la Casa de Aries!",            arc:"Santuario" },
      { num:29, title:"¡El Santo de Tauro: Aldebaran!",           arc:"Santuario" },
      { num:30, title:"¡La Pared de Diamante!",                   arc:"Santuario" },
      { num:31, title:"¡Shiryu Pierde la Vista!",                 arc:"Santuario" },
      { num:32, title:"¡Sagitario: La Casa del Arquero!",         arc:"Santuario" },
      { num:33, title:"¡El Cosmo de Gemelos!",                    arc:"Santuario" },
      { num:34, title:"¡La Otra Dimensión!",                      arc:"Santuario" },
      { num:35, title:"¡Shura: La Espada de Capricornio!",        arc:"Santuario" },
      { num:36, title:"¡El Secreto de la Casa de Cáncer!",        arc:"Santuario" },
      { num:37, title:"¡El Campo de Batalla de los Muertos!",     arc:"Santuario" },
      { num:38, title:"¡Leo: El León Dorado!",                    arc:"Santuario" },
      { num:39, title:"¡El Guerrero Desconocido de Virgo!",       arc:"Santuario" },
      { num:40, title:"¡Shaka: El Hombre Más Cercano a Dios!",   arc:"Santuario" },
      { num:41, title:"¡El Despertar del Octavo Sentido!",        arc:"Santuario" },
      { num:42, title:"¡La Casa de Libra: Las Armas Sagradas!",  arc:"Santuario" },
      { num:43, title:"¡Escorpio: El Veneno Mortal!",             arc:"Santuario" },
      { num:44, title:"¡Milo y la Aguja Escarlata!",              arc:"Santuario" },
      { num:45, title:"¡El Acuario: La Tumba de Hielo!",          arc:"Santuario" },
      { num:46, title:"¡Hyoga Vs Camus!",                         arc:"Santuario" },
      { num:47, title:"¡Pisces: El Santo del Amor!",              arc:"Santuario" },
      { num:48, title:"¡La Verdad del Gran Pontífice!",           arc:"Santuario" },
      { num:49, title:"¡Saga Revela su Rostro Maligno!",          arc:"Santuario" },
      { num:50, title:"¡La Flecha Dorada en el Corazón de Atenea!", arc:"Santuario" },
      { num:51, title:"¡Los Santos Caídos Resucitan!",            arc:"Santuario" },
      { num:52, title:"¡La Batalla Final en el Olimpo!",          arc:"Santuario" },
      { num:53, title:"¡El Cosmo del Amor Derrota el Mal!",       arc:"Santuario" },
      { num:54, title:"¡Saga Recupera su Alma!",                  arc:"Santuario" },
      { num:55, title:"¡La Paz Regresa al Santuario!",            arc:"Santuario" },
    ]
  },
  3: {
    title: "La Guerra de Asgard",
    subtitle: "Episodios 74–99 · 1988 · Los Guerreros Divinos",
    icon: "❄️",
    list: [
      { num:74, title:"¡El Ejército de Asgard!",                  arc:"Asgard" },
      { num:75, title:"¡Los Siete Guerreros Divinos!",            arc:"Asgard" },
      { num:76, title:"¡El Guerrero del Hielo: Hagen!",           arc:"Asgard" },
      { num:77, title:"¡La Tormenta de Asgard!",                  arc:"Asgard" },
      { num:78, title:"¡Syd: El Guerrero del Oso Mayor!",         arc:"Asgard" },
      { num:79, title:"¡El Poder de las Estrellas del Norte!",    arc:"Asgard" },
      { num:80, title:"¡Mime: La Música del Cosmos!",             arc:"Asgard" },
      { num:81, title:"¡La Melodía de la Muerte!",                arc:"Asgard" },
      { num:82, title:"¡Fenrir: El Guerrero de los Lobos!",       arc:"Asgard" },
      { num:83, title:"¡Seiya y los Lobos de Asgard!",            arc:"Asgard" },
      { num:84, title:"¡Thor: El Guerrero del Trueno!",           arc:"Asgard" },
      { num:85, title:"¡El Martillo de Thor!",                    arc:"Asgard" },
      { num:86, title:"¡Seiya Vs Thor: Batalla Épica!",           arc:"Asgard" },
      { num:87, title:"¡Alberich: El Guerrero de la Tierra!",     arc:"Asgard" },
      { num:88, title:"¡El Anillo de los Nibelungos!",            arc:"Asgard" },
      { num:89, title:"¡Sigurd: El Guerrero de Dubhe!",           arc:"Asgard" },
      { num:90, title:"¡La Verdad de Hilda!",                     arc:"Asgard" },
      { num:91, title:"¡El Anillo de Nibelung y Atenea!",         arc:"Asgard" },
      { num:92, title:"¡La Espada Sagrada Balmung!",              arc:"Asgard" },
      { num:93, title:"¡Seiya contra el Último Guerrero!",        arc:"Asgard" },
      { num:94, title:"¡El Cosmo de Asgard se Libera!",           arc:"Asgard" },
      { num:95, title:"¡El Fin de la Guerra de Asgard!",          arc:"Asgard" },
      { num:96, title:"¡Hilda Libre del Control!",                arc:"Asgard" },
      { num:97, title:"¡El Regreso a Japón!",                     arc:"Asgard" },
      { num:98, title:"¡El Nuevo Enemigo desde el Mar!",          arc:"Asgard" },
      { num:99, title:"¡Los Soldados del Océano!",                arc:"Asgard" },
    ]
  },
  4: {
    title: "La Guerra del Océano",
    subtitle: "Episodios 100–114 · 1989–1990 · Poseidón despierta",
    icon: "🌊",
    list: [
      { num:100, title:"¡El Despertar de Poseidón!",                arc:"Poseidón" },
      { num:101, title:"¡Las Columnas del Océano!",                 arc:"Poseidón" },
      { num:102, title:"¡Los Marinas de los Siete Mares!",          arc:"Poseidón" },
      { num:103, title:"¡Isla: El Marina del Mar del Norte!",       arc:"Poseidón" },
      { num:104, title:"¡El Dragón de las Profundidades!",          arc:"Poseidón" },
      { num:105, title:"¡Krishna: El Marina del Océano Índico!",   arc:"Poseidón" },
      { num:106, title:"¡El Escudo de Cristal!",                    arc:"Poseidón" },
      { num:107, title:"¡Seiya Cae ante Poseidón!",                 arc:"Poseidón" },
      { num:108, title:"¡La Balanza de Libra al Fondo del Mar!",    arc:"Poseidón" },
      { num:109, title:"¡La Gran Columna del Atlántico!",           arc:"Poseidón" },
      { num:110, title:"¡Sea Dragon: El Más Poderoso Marina!",      arc:"Poseidón" },
      { num:111, title:"¡El Último Enemigo antes de Poseidón!",     arc:"Poseidón" },
      { num:112, title:"¡La Batalla Final contra el Dios del Mar!", arc:"Poseidón" },
      { num:113, title:"¡El Cosmo de Atenea!",                      arc:"Poseidón" },
      { num:114, title:"¡Atenea Sella a Poseidón!",                 arc:"Poseidón" },
    ]
  },
  5: {
    title: "OVAs — El Inframundo de Hades",
    subtitle: "13 OVAs · 2002–2008 · El clímax definitivo",
    icon: "💀",
    list: [
      { num:1,  title:"¡El Ejército de los Espectros!",             arc:"Hades: Elíseo" },
      { num:2,  title:"¡Los Santos de Oro Traicionan!",             arc:"Hades: Elíseo" },
      { num:3,  title:"¡Seiya Cae ante los Espectros!",             arc:"Hades: Elíseo" },
      { num:4,  title:"¡El Plan Secreto de los Santos de Oro!",     arc:"Hades: Elíseo" },
      { num:5,  title:"¡La Mansión de Hades!",                      arc:"Hades: Inframundo" },
      { num:6,  title:"¡El Décimo Sentido!",                        arc:"Hades: Inframundo" },
      { num:7,  title:"¡Shaka Vs los Tres Jueces!",                 arc:"Hades: Inframundo" },
      { num:8,  title:"¡El Sacrificio de los Santos de Oro!",       arc:"Hades: Inframundo" },
      { num:9,  title:"¡Las Murallas del Inframundo!",              arc:"Hades: Elíseo" },
      { num:10, title:"¡Hades: El Dios de la Muerte!",              arc:"Hades: Elíseo" },
      { num:11, title:"¡El Cosmo Infinito!",                        arc:"Hades: Elíseo" },
      { num:12, title:"¡Seiya Alcanza los Dioses!",                  arc:"Hades: Elíseo" },
      { num:13, title:"¡La Luz del Amanecer: Atenea Triunfa!",      arc:"Hades: Elíseo" },
    ]
  }
};
